### ISSUE TITLE
essential php extension for phalcon

### ISSUE THREAD

**Issue by nghenglim** [elct9620/heroku-buildpacks-php-with-phalcon#1]
mbstring is used by the templating engine (Volt) that Phalcon has as well as some validators, the escaper and the filter.

maybe you can include it in the next release

**Comment by elct9620** [comment]
Hello, I create a new version "0.2.0-alpha" and add mbstring support.

Just push your code to heroku, and it will auto using new version pre-compile pacakge.
( New version I add into develop branch, make sure you are using develop branch's buildpacks )
